### ISSUE TITLE
Funcionalidade musica

### ISSUE THREAD

**Issue by izauir** [izauir/botMemets#1]
- [x] Criar comando `/play`
- [x] Conectar no canal de voz onde o usuário que executou o comando estiver.
- [ ] Executar o link de música do youtube no canal de voz, comando: `/play "link"`
